languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Titto Thommy"
  title = "Titto Thommy's Resume"
  description = "Titto Thommy's Awesome Resume"
  avatar = "TittoProfilePicture.jpg"
  email_full = "mailto:titto.thommy@gmail.com?subject=Got your resume"
  github = "tittothommy"
  linkedin = "titto"
  google_maps = "https://www.google.com/maps/place/Amstelveen"
  city = "Amstelveen"
  country = "The Netherlands"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []